.
======================================================================
ERROR: test_login_cases (__main__.test_login) (row={'comments': '使用phone登录成功', 'password': '123456', 'username': '', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'res': '10001', 'sessionid': '', 'guid': '', 'mail': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 76, in test_login_cases
    response_dict = eval(response.read())
  File "<string>", line 1, in <module>
NameError: name 'null' is not defined

======================================================================
FAIL: test_addusername_cases (__main__.test_addusername) (row={'comments': 'guid为空且phone为空', 'password': '', 'username': 'qatesta', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '', 'res': '10011', 'guid': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 251, in test_addusername_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #完善用户名模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10005 != 10011

======================================================================
FAIL: test_bindphone_cases (__main__.test_bindphone) (row={'code_id': '123456', 'comments': 'code_id错误', 'password': '123456', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'res': '10014', 'guid': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 198, in test_bindphone_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #绑定手机模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10011 != 10014

======================================================================
FAIL: test_changepwdbycode_cases (__main__.test_changepwdbycode) (row={'code_id': '123456', 'comments': 'code_id错误', 'password': '123456', 'username': 'testblind', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'res': '10014'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 170, in test_changepwdbycode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #找回密码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10011 != 10014

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'comments': 'appid为空', 'gender': '', 'nickname': '', 'job': '', 'industry': '', 'education': '', 'address': '', 'username': 'qatest1', 'appid': '', 'province': '', 'postcode': '', 'res': '10002', 'income': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10002

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'comments': 'appid错误', 'gender': '', 'nickname': '', 'job': '', 'industry': '', 'education': '', 'address': '', 'username': 'qatest1', 'appid': 'wrongappid', 'province': '', 'postcode': '', 'res': '10002', 'income': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10002

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'comments': 'username不存在', 'gender': '', 'nickname': '', 'job': '', 'industry': '', 'education': '', 'address': '', 'username': 'testnothere', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'province': '', 'postcode': '', 'res': '10009', 'income': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10009

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'comments': 'nickname非法字符', 'gender': '', 'nickname': 'nickname#$', 'job': '', 'industry': '', 'education': '', 'address': '', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'province': '', 'postcode': '', 'res': '10011', 'income': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'comments': 'postcode非法', 'gender': '', 'nickname': '', 'job': '', 'industry': '', 'education': '', 'address': '', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'province': '', 'postcode': 'post#$', 'res': '10011', 'income': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'comments': 'postcode非法', 'gender': '', 'nickname': '', 'job': '', 'industry': '', 'education': '', 'address': '', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'province': '', 'postcode': '123', 'res': '10011', 'income': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'comments': 'address非法', 'gender': '', 'nickname': '', 'job': '', 'industry': '', 'education': '', 'address': 'address@#$', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'province': '', 'postcode': '', 'res': '10011', 'income': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'comments': 'province非法', 'gender': '', 'nickname': '', 'job': '', 'industry': '', 'education': '', 'address': '', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'province': '0', 'postcode': '', 'res': '10011', 'income': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10001 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'comments': 'province非法', 'gender': '', 'nickname': '', 'job': '', 'industry': '', 'education': '', 'address': '', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'province': '99', 'postcode': '', 'res': '10011', 'income': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10011

======================================================================
FAIL: test_editinfo_cases (__main__.test_editinfo) (row={'comments': 'province非法', 'gender': '', 'nickname': '', 'job': '', 'industry': '', 'education': '', 'address': '', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'province': '$%', 'postcode': '', 'res': '10011', 'income': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 225, in test_editinfo_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #修改信息模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10011

======================================================================
FAIL: test_findbindphone_cases (__main__.test_findbindphone) (row={'res': '10001', 'comments': 'appid正确且成功', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 104, in test_findbindphone_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取绑定手机模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10001

======================================================================
FAIL: test_findbindphone_cases (__main__.test_findbindphone) (row={'res': '10001', 'comments': 'username正确且成功', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 104, in test_findbindphone_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取绑定手机模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10000 != 10001

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'comments': 'code_type为空', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'res': '10012', 'guid': '', 'code_type': ''})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10017 != 10012

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'comments': 'code_type非法-0', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'res': '10012', 'guid': '', 'code_type': '0'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10017 != 10012

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'comments': 'code_type非法-3', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'res': '10012', 'guid': '', 'code_type': '3'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10008 != 10012

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'comments': 'code_type非法字符', 'username': 'qatest1', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'res': '10012', 'guid': '', 'code_type': '%'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10017 != 10012

======================================================================
FAIL: test_getcode_cases (__main__.test_getcode) (row={'comments': 'username为空使用guid成功', 'username': '', 'appid': '4e7dHsOyi5QjgpiBiemIreX74f7VgUCg7L', 'phone': '15692005742', 'res': '10001', 'guid': 'thisisguid', 'code_type': '1'})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Passport_Interface_Testing.py", line 137, in test_getcode_cases
    self.assertEqual(response_dict["res"], eval(row['res']))    #获取验证码模块---您看到此信息,代表当行测试数据未通过---
AssertionError: 10003 != 10001

----------------------------------------------------------------------
Ran 8 tests in 16.934s

FAILED (failures=20, errors=1)
